### ISSUE TITLE
Problems with the data when analyzing the replays of the lazer version

### ISSUE THREAD

**Issue by Diamochang** [minisbett/holdtimeanalyzer#1]
I've been playing with lazer since I returned to osu! in July this year. However, when I use this software to analyze hold-time, the results are not very good:

- The results are only for Key 2
- The numbers in parentheses in the header of the table are not displayed correctly

I went on to analyze with two more replays and had the same problem. I think it is possible that the software was designed for the stable version only, and the lazer's replay file has been tweaked in some way to cause these problems.
In case my description is still not intuitive, here are the data from the three replays analyzed by the software and the AG Analyzer:

1. Time Alter [Easy] ([osu! web](https://osu.ppy.sh/scores/3281152891))

![solo-replay-osu_1773167_3281152891](https://github.com/user-attachments/assets/82283a06-3c77-4bb2-b757-06a086fa7835)
![solo-replay-osu_1773167_3281152891_ag](https://github.com/user-attachments/assets/b6fc8a3d-7bb2-43fb-8649-4ea0ea7e717f)

2. Metamoru [Normal] with HR ([osu! web](https://osu.ppy.sh/scores/3324019523))

![solo-replay-osu_201574_3324019523](https://github.com/user-attachments/assets/cc6530e2-ab53-4111-bad4-5833b3c4832c)
![solo-replay-osu_201574_3324019523_ag](https://github.com/user-attachments/assets/4b06e9ab-d4c1-4844-8e6a-665af9210fd1)

3. seal the 3rd.mp4 [Easy] with HR ([osu! web](https://osu.ppy.sh/scores/3335700368))

![solo-replay-osu_941038_3335700368](https://github.com/user-attachments/assets/38869223-e2fe-459f-81e6-6277c3b4a6a0)
![solo-replay-osu_941038_3335700368_ag](https://github.com/user-attachments/assets/b127a9ef-ad81-4f04-ad87-093be3055869)

**Comment by minisbett** [comment]
Everything seems to work as intended. The only difference here is that my holdtime analyzer always displays the fixed range of 0ms to 100ms, while the AG website displays all of it.
I've done this mostly for display purposes and because this software was made with DKS in mind, and only that range really mattered.

As for the numbers in the parantheses, if you're referring to the first one showing -1, this is the online score ID, which appears to not be included or saved somewhere different in the replay file on Lazer, as the parser for replay files specifically targets the legacy replay format.

**Comment by Diamochang** [comment]
Thanks for the explanation :)
